[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend for the EURAU multichain monitor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "web3[tester]",
    "python-dotenv",
    "pytest>=8.3.2"
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
