name: Compile and test the backend

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

    pull_request:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    backend:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Install Python
              run: uv python install
            
            - name: Install dependencies
              run: uv sync --locked

            - name: Compile check
              run: uv run python -m compileall backend

            - name: Run tests
              run: uv run pytest